apiVersion: v1
kind: Service
metadata:
  name: guild-scroll-app
  namespace: guild-scroll
  labels:
    app: guild-scroll
    component: app
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  selector:
    app: guild-scroll
    component: app
---
apiVersion: v1
kind: Service
metadata:
  name: kali-recorder
  namespace: guild-scroll
  labels:
    app: guild-scroll
    component: recorder
spec:
  clusterIP: None
  selector:
    app: guild-scroll
    component: recorder
